"""update

Revision ID: 65caf8d4bfc5
Revises: fa1557578dcf
Create Date: 2026-05-15 23:38:28.396242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65caf8d4bfc5'
down_revision = 'fa1557578dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musica_playlist',
    sa.Column('musica_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ordem_na_playlist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musica_id'], ['musica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id', 'usuario_id'], ['playlist.playlist_id', 'playlist.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('musica_id', 'playlist_id', 'usuario_id'),
    sa.UniqueConstraint('playlist_id', 'usuario_id', 'ordem_na_playlist')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musica_playlist')
    # ### end Alembic commands ###
