"""update musica

Revision ID: b3f70af3b397
Revises: d847a5a899ad
Create Date: 2026-05-15 21:13:01.640195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f70af3b397'
down_revision = 'd847a5a899ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musica')
    # ### end Alembic commands ###
