"""update

Revision ID: fa1557578dcf
Revises: b3f70af3b397
Create Date: 2026-05-15 23:37:24.970126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa1557578dcf'
down_revision = 'b3f70af3b397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
